Repository milieuinfo/webcomponent-vl-ui-template, pull requests merged in 2020-07, with the labels that each got.

#70 Update dependency @govflanders/vl-ui-core to v3.10.1
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#71 Introductie nieuw Vlaanderen icon font
  package-lock.json
  package.json
  src/style.css
Labels: bug

#72 Update vl-ui-util
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
Labels: chore

#73 Update dependencies
  package-lock.json
  package.json
Labels: chore
