Repository milieuinfo/webcomponent-vl-ui-template, pull requests merged in 2020-04, with the labels that each got.

#53 Update dependency vl-ui-util to v5.1.5
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#58 Update vl-ui-util
  .mocharc.js
  bamboo-specs/bamboo.yml
  docker-compose-performance-chrome.yml
  docker-compose-performance-firefox.yml
  package-lock.json
  package.json
  performance/README.md
  performance/config/budget.json
  performance/config/config-chrome.json
  performance/config/config-firefox.json
  performance/scripts/preScript.js
Labels: chore

#59 Wanneer er weinig context is moet de footer onderaan de pagina getoond worden
  package-lock.json
  src/style.css
  src/style.scss
  src/vl-template.js
  test/unit/vl-template.test.html
Labels: bug

#60 Update dependency @govflanders/vl-ui-core to v3.9.2
  package-lock.json
  package.json
Labels: chore, dependencies, renovate
